name: local_audio_subtitles
description: Flutter audio player with local DB and SRT subtitles
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.39
  sqflite: ^2.3.3
  path_provider: ^2.1.5
  file_picker: ^8.0.5
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
